### ISSUE TITLE
! Item not available - try again !

### ISSUE THREAD

**Issue by wimstefan** [JohnFawkes/fontchanger#1] opened 2019-06-05 12:29 UTC
Thank you for realizing an app like this! Unfortunately I can't install any custom fonts :-/
That's the message I get when I try to install a custom font via Menu -> List Fonts in Folder
The fonts are installed as described ...

```=========================
Xiami Redmi Note4, P3QA.190605.003
=========================
BUSYBOX Version = v1.22.1 bionic
=========================
MAGISK VERSION = 19.3
=========================
```

**Comment by JohnFawkes** [comment] 2019-06-08 03:56
> Thank you for realizing an app like this! Unfortunately I can't install any custom fonts :-/
> That's the message I get when I try to install a custom font via Menu -> List Fonts in Folder
> The fonts are installed as described ...
> 
> ```
> Xiami Redmi Note4, P3QA.190605.003
> =========================
> BUSYBOX Version = v1.22.1 bionic
> =========================
> MAGISK VERSION = 19.3
> =========================
> ```

I will look into the issue. thanks.

**Comment by wimstefan** [comment] 2019-06-08 11:24
Thank you so much!
Please let me know if you need more information from me ...

**Comment by JohnFawkes** [comment] 2019-06-08 11:55
> Thank you so much!
> Please let me know if you need more information from me ...

Yes can you send me /cache/Fontchanger-verbose.log please? And also take a screenshot of /data/media/0/Fontchanger/Fonts/Custom please? I tested custom fonts last night and everything was working just fine so not exactly sure what the issue is

**Comment by wimstefan** [comment] 2019-06-08 12:24
Of course. Here you go...

**Comment by wimstefan** [comment] 2019-06-08 12:35
Hmmm
Of course  here you go 

...

**Comment by JohnFawkes** [comment] 2019-06-08 12:37
If your having trouble uploading here just send them via email to me at skaterdudebradley@gmail.com

**Comment by JohnFawkes** [comment] 2019-06-14 18:09
closing since issue was resolved via email

**Closed by JohnFawkes** 2019-06-14 18:09 UTC
